FORMAT: 1A
HOST: https://testapi.linc.world/v1

# Linc API

# Group Authorization
## oAuth2 Password Grant [/auth/token]
### Get Token/Login [POST]
    
+ Request (application/x-www-form-urlencoded)
        
    + Form Data

        + grant_type: "password"
        + username: <user_email>
        + password: <user_password>
            
    + Headers

            Authorization: Basic <clientID>:<clientSecret>
            
    + Body
            
            grant_type=password&username=name%40email.com&password=password

+ Response 200 (application/json)
    
    + Body
        
            {
                "access_token": "3sedq3otrh1qfsj61bljkpkjr7eqr3ggkh9b614",
                "token_type": "Bearer",
                "expires_in": 3599,
                "refresh_token": "ieosthc9h1dksne0d0l7llqaig47sl9anaml73103q1ipoj40i512k10o"
            }

# Group Users

## User Signup [/users/]

### Signup [POST]
    
+ Request (application/x-www-form-urlencoded)
        
    + Form Data

        + name: <user_name>
        + email: <user_email>
        + password: <user_password>
        + username: <user_username>
            
    + Headers

            Authorization: Basic <clientID>:<clientSecret>
            
    + Body
    
            name=User%20Name&email=name%40email.com&password=password&username=username

+ Response 200 (application/json)
    
    + Body
        
            {
                "access_token": "3sedq3otrh1qfsj61bljkpkjr7eqr3ggkh9b614",
                "token_type": "Bearer",
                "expires_in": 3599,
                "refresh_token": "ieosthc9h1dksne0d0l7llqaig47sl9anaml73103q1ipoj40i512k10o"
            }

## User [/users/{id}]
### Get User [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "54A0117ABD2BE3F251C3492A",
                "name": "Afzaal Ameer",
                "username": "afzaalace",
                "title": "Some Title",
                "bio": "Lorem ipsum dolor met.",
                "location": "Madrid, Madrid, Spain",
                "followers_count": 5,
                "followings_count": 2,
                "leafs_count": 5,
                "membersince": "2014-12-28T14:19:38.000Z",
                "rev": 5,
                "website": "http://www.afzaalace.com",
                "facebook": "https://www.facebook.com/pixelexploiter",
                "google": "https://plus.google.com/+AfzaalAmeer",
                "twitter": "http://twitter.com/afzaalace",
                "linkedin": "http://in.linkedin.com/in/afzaalace",
                "pinterest": "",
                "views": 164,
                "posted_count": 2,
                "following_state": false,
                "interests": {
                    "sectors": [
                        {
                            "Sector": "Energy",
                            "Share": 86
                        },
                        {
                            "Sector": "Economy",
                            "Share": 50
                        },
                        {
                            "Sector": "Renewable",
                            "Share": 48
                        },
                        {
                            "Sector": "Tage Name",
                            "Share": 45
                        },
                        {
                            "Sector": "Water",
                            "Share": 42
                        }
                    ]
                },
                "image": "https://cdn.linc.world/users/profile-54A0117ABD2BE3F251C3492A.jpg",
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    },
                    "activities": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/activities"
                    },
                    "followers": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/followers"
                    },
                    "following": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/following"
                    },
                    "posts": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/posts"
                    }
                }
            }

### Followers [/users/{id}/followers{?page,size}]
#### Get Followers [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "users": [
                    {
                        "id": "54A05594DFE5D181114C762A",
                        "name": "Pranay Krishen",
                        "username": "pranay",
                        "title": "Founder | Linc",
                        "bio": "Founder of Linc.world - media, community and resource management platform to support global sustainable development.<br/><br/>Previously, built and raced a solar-powered race car across the 3021km Australian Outback; served as Canada’s cleantech trade ambassador to Brazil; led the deployment of eco-schools across Jordan; researched advanced smart-grid and energy storage solutions with the FP7 commission in Greece; built a green-building residential complex in India; and founded EcoAlliance Cleantech, a photovoltaic systems integrator.<br/><br/>Mechatronics Engineering and Business graduate from Western University in Canada. Designated P.Eng. (EIT) and LEED AP. Lived and worked in Canada, India, Jordan, Chile, Brazil, UK, Denmark and Spain.",
                        "location": "Madrid, Madrid, Spain",
                        "followers_count": 21,
                        "followings_count": 71,
                        "leafs_count": 65,
                        "posted_count": 86,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "http://www.linc.world",
                        "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A05594DFE5D181114C762A"
                            },
                            "activities": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                            }
                        }
                    },
                    {
                        "id": "580667C5F324DBE8290FA3A9",
                        "name": "Danny Saltaren",
                        "username": "",
                        "title": "",
                        "bio": "Freelance Senior Product Designer",
                        "location": "Madrid Area, Spain",
                        "followers_count": 1,
                        "followings_count": 3,
                        "leafs_count": 0,
                        "posted_count": 0,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "",
                        "image": "https://cdn.linc.world/users/profile-580667C5F324DBE8290FA3A9.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9"
                            },
                            "activities": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/activities"
                            },
                            "followers": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/followers"
                            },
                            "following": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/following"
                            },
                            "posts": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/posts"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/followers"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }

### Following [/users/{id}/following{?page,size}]
#### Get Following [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "users": [
                    {
                        "id": "54A0E4F54908B9D84E87E4A4",
                        "name": "Manu Akash",
                        "username": "ManuAkash",
                        "title": "UX/UI Engineer at GO-JEK",
                        "bio": "I believe strongly in keeping up with, and applying the latest design and technical trends to drive innovation via my work.As a true practitioner of the Latin phrase: \"ACTO NON VERBA\", I believe in letting my efforts speak for themselves.",
                        "location": "Bangalore, Karnataka, India",
                        "followers_count": 4,
                        "followings_count": 6,
                        "leafs_count": 148,
                        "posted_count": 229,
                        "membersince": "2014-12-29T05:21:57.000Z",
                        "website": "",
                        "image": "https://cdn.linc.world/users/profile-54A0E4F54908B9D84E87E4A4.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4"
                            },
                            "activities": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/posts"
                            }
                        }
                    },
                    {
                        "id": "54A05594DFE5D181114C762A",
                        "name": "Pranay Krishen",
                        "username": "pranay",
                        "title": "Founder | Linc",
                        "bio": "Founder of Linc.world - media, community and resource management platform to support global sustainable development.<br/><br/>Previously, built and raced a solar-powered race car across the 3021km Australian Outback; served as Canada’s cleantech trade ambassador to Brazil; led the deployment of eco-schools across Jordan; researched advanced smart-grid and energy storage solutions with the FP7 commission in Greece; built a green-building residential complex in India; and founded EcoAlliance Cleantech, a photovoltaic systems integrator.<br/><br/>Mechatronics Engineering and Business graduate from Western University in Canada. Designated P.Eng. (EIT) and LEED AP. Lived and worked in Canada, India, Jordan, Chile, Brazil, UK, Denmark and Spain.",
                        "location": "Madrid, Madrid, Spain",
                        "followers_count": 21,
                        "followings_count": 71,
                        "leafs_count": 65,
                        "posted_count": 86,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "http://www.linc.world",
                        "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A05594DFE5D181114C762A"
                            },
                            "activities": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/following"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }

### User Posts [/users/{id}/posts{?page,size}]
#### Get Posts [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "posts": [
                    {
                        "id": "54C74FA58B8FC61F3809F677",
                        "source": "http://www.huffingtonpost.com/nicole-lederer/military-private-sector-a_b_6369094.html",
                        "title": "Military, Private Sector Are Close Partners in Securing America's Clean Energy Future",
                        "description": "The military has ambitious energy goals - like the Navy sourcing 50 percent of its on-shore energy from alternative sources by 2020, or the Army and Air Force each aiming to have 1 GW of renewable energy installed on their bases by 2025.",
                        "created_date": "2015-01-27T08:43:17.000Z",
                        "image": "https://cdn.linc.world/articles/54C74FA58B8FC61F3809F677.jpg",
                        "rev": 0,
                        "height": 252,
                        "views_count": 384,
                        "leafs_count": 3,
                        "comments_count": 0,
                        "shortURL": "4g",
                        "timestamp": "2017-01-16T15:02:44.000Z",
                        "_links": {
                            "self": {
                                "href": "/v1/posts/54C74FA58B8FC61F3809F677"
                            },
                            "comments": {
                                "href": "/v1/posts/54C74FA58B8FC61F3809F677/comments"
                            }
                        }
                    },
                    {
                        "id": "54A0161EB72B1BBF60F5A0B4",
                        "source": "http://ensia.com/notable/treating-environmental-crime-like-other-crime/",
                        "title": "Treating environmental crime like other crime",
                        "description": "The illegal exportation of waste throughout the European Union, the trafficking of endangered species, and surface-water pollution were all recognized in a&hellip;",
                        "created_date": "2014-12-28T14:39:26.000Z",
                        "image": "https://cdn.linc.world/articles/54A0161EB72B1BBF60F5A0B4.jpg",
                        "rev": 0,
                        "height": 288,
                        "views_count": 462,
                        "leafs_count": 2,
                        "comments_count": 0,
                        "shortURL": "1",
                        "timestamp": "2017-01-16T15:03:49.000Z",
                        "_links": {
                            "self": {
                                "href": "/v1/posts/54A0161EB72B1BBF60F5A0B4"
                            },
                            "comments": {
                                "href": "/v1/posts/54A0161EB72B1BBF60F5A0B4/comments"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/posts"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }


# Group Posts

## Post [/posts/{id}]
### Get Post [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "581DEDEA002B74604FE091C1",
                "source": "http://www.autonews.com/article/20161104/OEM05/161109912/teslas-solarcity-deal-gets-a-boost-from-shareholder-advisory-firm",
                "title": "Tesla's SolarCity deal gets a boost from shareholder advisory firm",
                "owner": {
                    "name": "Dan Rogers",
                    "id": "55195B5A0BD9E6AC218174AC",
                    "username": "danrogers",
                    "title": "Co-Founder of Linc",
                    "bio": "",
                    "location": "Madrid, Madrid, Spain",
                    "followers_count": 6,
                    "followings_count": 4,
                    "leafs_count": 48,
                    "membersince": "2015-03-30T14:19:06.000Z",
                    "rev": 2,
                    "website": "",
                    "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                    "_links": {
                        "self": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                        },
                        "activities": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                        },
                        "followers": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                        },
                        "following": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                        },
                        "posts": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                        }
                    }
                },
                "description": "Institutional Shareholder Services today recommended that investors in both companies approve Tesla Motors' plan to buy solar panel installer SolarCity for more than $2 billion.",
                "created_date": "2016-11-05T14:34:18.000Z",
                "image": "https://cdn.linc.world/articles/581DEDEA002B74604FE091C1.jpg",
                "rev": 0,
                "height": 172,
                "views_count": 41,
                "leafs_count": 0,
                "comments_count": 0,
                "shortURL": "BG",
                "timestamp": "2017-01-13T00:58:55.000Z",
                "leaf_state": false,
                "_links": {
                    "self": {
                        "href": "/v1/posts/581DEDEA002B74604FE091C1"
                    },
                    "comments": {
                        "href": "/v1/posts/581DEDEA002B74604FE091C1/comments"
                    }
                }
            }