FORMAT: 1A
HOST: https://testapi.linc.world/v1

# Linc API

# Group Authorization
## oAuth2 Password Grant [/auth/token]
### Get Token/Login [POST]
    
+ Request (application/x-www-form-urlencoded)
        
    + Form Data

        + grant_type: "password"
        + username: <user_email>
        + password: <user_password>
            
    + Headers

            Authorization: Basic <clientID>:<clientSecret>
            
    + Body
            
            grant_type=password&username=name%40email.com&password=password

+ Response 200 (application/json)
    
    + Body
        
            {
                "access_token": "3sedq3otrh1qfsj61bljkpkjr7eqr3ggkh9b614",
                "token_type": "Bearer",
                "expires_in": 3599,
                "refresh_token": "ieosthc9h1dksne0d0l7llqaig47sl9anaml73103q1ipoj40i512k10o"
            }

# Group Users

## User Signup [/users/]

### Signup [POST]
    
+ Request (application/x-www-form-urlencoded)
        
    + Form Data

        + name: <user_name>
        + email: <user_email>
        + password: <user_password>
        + username: <user_username>
            
    + Headers

            Authorization: Basic <clientID>:<clientSecret>
            
    + Body
    
            name=User%20Name&email=name%40email.com&password=password&username=username

+ Response 200 (application/json)
    
    + Body
        
            {
                "access_token": "3sedq3otrh1qfsj61bljkpkjr7eqr3ggkh9b614",
                "token_type": "Bearer",
                "expires_in": 3599,
                "refresh_token": "ieosthc9h1dksne0d0l7llqaig47sl9anaml73103q1ipoj40i512k10o"
            }

## User [/users/{id}]
### Get User [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "54A0117ABD2BE3F251C3492A",
                "name": "Afzaal Ameer",
                "username": "afzaalace",
                "title": "Some Title",
                "bio": "Lorem ipsum dolor met.",
                "location": "Madrid, Madrid, Spain",
                "followers_count": 5,
                "followings_count": 2,
                "leafs_count": 5,
                "membersince": "2014-12-28T14:19:38.000Z",
                "rev": 5,
                "website": "http://www.afzaalace.com",
                "facebook": "https://www.facebook.com/pixelexploiter",
                "google": "https://plus.google.com/+AfzaalAmeer",
                "twitter": "http://twitter.com/afzaalace",
                "linkedin": "http://in.linkedin.com/in/afzaalace",
                "pinterest": "",
                "views": 164,
                "posted_count": 2,
                "following_state": false,
                "interests": {
                    "sectors": [
                        {
                            "Sector": "Energy",
                            "Share": 86
                        },
                        {
                            "Sector": "Economy",
                            "Share": 50
                        },
                        {
                            "Sector": "Renewable",
                            "Share": 48
                        },
                        {
                            "Sector": "Tage Name",
                            "Share": 45
                        },
                        {
                            "Sector": "Water",
                            "Share": 42
                        }
                    ]
                },
                "image": "https://cdn.linc.world/users/profile-54A0117ABD2BE3F251C3492A.jpg",
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    },
                    "activities": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/activities"
                    },
                    "followers": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/followers"
                    },
                    "following": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/following"
                    },
                    "posts": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/posts"
                    }
                }
            }

### Followers [/users/{id}/followers{?page,size}]
#### Get Followers [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "users": [
                    {
                        "id": "54A05594DFE5D181114C762A",
                        "name": "Pranay Krishen",
                        "username": "pranay",
                        "title": "Founder | Linc",
                        "bio": "Founder of Linc.world - media, community and resource management platform to support global sustainable development.<br/><br/>Previously, built and raced a solar-powered race car across the 3021km Australian Outback; served as Canada’s cleantech trade ambassador to Brazil; led the deployment of eco-schools across Jordan; researched advanced smart-grid and energy storage solutions with the FP7 commission in Greece; built a green-building residential complex in India; and founded EcoAlliance Cleantech, a photovoltaic systems integrator.<br/><br/>Mechatronics Engineering and Business graduate from Western University in Canada. Designated P.Eng. (EIT) and LEED AP. Lived and worked in Canada, India, Jordan, Chile, Brazil, UK, Denmark and Spain.",
                        "location": "Madrid, Madrid, Spain",
                        "followers_count": 21,
                        "followings_count": 71,
                        "leafs_count": 65,
                        "posted_count": 86,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "http://www.linc.world",
                        "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A05594DFE5D181114C762A"
                            },
                            "activities": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                            }
                        }
                    },
                    {
                        "id": "580667C5F324DBE8290FA3A9",
                        "name": "Danny Saltaren",
                        "username": "",
                        "title": "",
                        "bio": "Freelance Senior Product Designer",
                        "location": "Madrid Area, Spain",
                        "followers_count": 1,
                        "followings_count": 3,
                        "leafs_count": 0,
                        "posted_count": 0,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "",
                        "image": "https://cdn.linc.world/users/profile-580667C5F324DBE8290FA3A9.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9"
                            },
                            "activities": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/activities"
                            },
                            "followers": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/followers"
                            },
                            "following": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/following"
                            },
                            "posts": {
                                "href": "/v1/users/580667C5F324DBE8290FA3A9/posts"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/followers"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }

### Following [/users/{id}/following{?page,size}]
#### Get Following [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "users": [
                    {
                        "id": "54A0E4F54908B9D84E87E4A4",
                        "name": "Manu Akash",
                        "username": "ManuAkash",
                        "title": "UX/UI Engineer at GO-JEK",
                        "bio": "I believe strongly in keeping up with, and applying the latest design and technical trends to drive innovation via my work.As a true practitioner of the Latin phrase: \"ACTO NON VERBA\", I believe in letting my efforts speak for themselves.",
                        "location": "Bangalore, Karnataka, India",
                        "followers_count": 4,
                        "followings_count": 6,
                        "leafs_count": 148,
                        "posted_count": 229,
                        "membersince": "2014-12-29T05:21:57.000Z",
                        "website": "",
                        "image": "https://cdn.linc.world/users/profile-54A0E4F54908B9D84E87E4A4.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4"
                            },
                            "activities": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A0E4F54908B9D84E87E4A4/posts"
                            }
                        }
                    },
                    {
                        "id": "54A05594DFE5D181114C762A",
                        "name": "Pranay Krishen",
                        "username": "pranay",
                        "title": "Founder | Linc",
                        "bio": "Founder of Linc.world - media, community and resource management platform to support global sustainable development.<br/><br/>Previously, built and raced a solar-powered race car across the 3021km Australian Outback; served as Canada’s cleantech trade ambassador to Brazil; led the deployment of eco-schools across Jordan; researched advanced smart-grid and energy storage solutions with the FP7 commission in Greece; built a green-building residential complex in India; and founded EcoAlliance Cleantech, a photovoltaic systems integrator.<br/><br/>Mechatronics Engineering and Business graduate from Western University in Canada. Designated P.Eng. (EIT) and LEED AP. Lived and worked in Canada, India, Jordan, Chile, Brazil, UK, Denmark and Spain.",
                        "location": "Madrid, Madrid, Spain",
                        "followers_count": 21,
                        "followings_count": 71,
                        "leafs_count": 65,
                        "posted_count": 86,
                        "membersince": "2014-12-28T19:10:12.000Z",
                        "website": "http://www.linc.world",
                        "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                        "_links": {
                            "self": {
                                "href": "/v1/users/54A05594DFE5D181114C762A"
                            },
                            "activities": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                            },
                            "followers": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                            },
                            "following": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/following"
                            },
                            "posts": {
                                "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/following"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }

### User Posts [/users/{id}/posts{?page,size}]
#### Get Posts [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A0117ABD2BE3F251C3492A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "posts": [
                    {
                        "id": "54C74FA58B8FC61F3809F677",
                        "source": "http://www.huffingtonpost.com/nicole-lederer/military-private-sector-a_b_6369094.html",
                        "title": "Military, Private Sector Are Close Partners in Securing America's Clean Energy Future",
                        "description": "The military has ambitious energy goals - like the Navy sourcing 50 percent of its on-shore energy from alternative sources by 2020, or the Army and Air Force each aiming to have 1 GW of renewable energy installed on their bases by 2025.",
                        "created_date": "2015-01-27T08:43:17.000Z",
                        "image": "https://cdn.linc.world/articles/54C74FA58B8FC61F3809F677.jpg",
                        "rev": 0,
                        "height": 252,
                        "views_count": 384,
                        "leafs_count": 3,
                        "comments_count": 0,
                        "shortURL": "4g",
                        "timestamp": "2017-01-16T15:02:44.000Z",
                        "_links": {
                            "self": {
                                "href": "/v1/posts/54C74FA58B8FC61F3809F677"
                            },
                            "comments": {
                                "href": "/v1/posts/54C74FA58B8FC61F3809F677/comments"
                            }
                        }
                    },
                    {
                        "id": "54A0161EB72B1BBF60F5A0B4",
                        "source": "http://ensia.com/notable/treating-environmental-crime-like-other-crime/",
                        "title": "Treating environmental crime like other crime",
                        "description": "The illegal exportation of waste throughout the European Union, the trafficking of endangered species, and surface-water pollution were all recognized in a&hellip;",
                        "created_date": "2014-12-28T14:39:26.000Z",
                        "image": "https://cdn.linc.world/articles/54A0161EB72B1BBF60F5A0B4.jpg",
                        "rev": 0,
                        "height": 288,
                        "views_count": 462,
                        "leafs_count": 2,
                        "comments_count": 0,
                        "shortURL": "1",
                        "timestamp": "2017-01-16T15:03:49.000Z",
                        "_links": {
                            "self": {
                                "href": "/v1/posts/54A0161EB72B1BBF60F5A0B4"
                            },
                            "comments": {
                                "href": "/v1/posts/54A0161EB72B1BBF60F5A0B4/comments"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A/posts"
                    },
                    "user": {
                        "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                    }
                }
            }

### User Leafed Posts [/users/{id}/leafed{?page,size}]
#### Get Leafed Posts [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A05594DFE5D181114C762A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "posts": [
                    {
                        "post": {
                            "id": "582C59ED4A46D6D7064643C8",
                            "source": "http://www.yachtingworld.com/features/solo-across-the-atlantic-in-a-folkboat-67743",
                            "title": "Solo across the Atlantic in a Folkboat – Yachting World",
                            "description": "Carrying his guitar, some fine wine, an old French racing bike and a sextant, Leo Goolden sets out on his first solo Atlantic crossing in a 24ft Folkboat",
                            "created_date": "2016-11-16T13:06:53.000Z",
                            "image": "https://cdn.linc.world/articles/582C59ED4A46D6D7064643C8.jpg",
                            "rev": 0,
                            "views_count": 45,
                            "leafs_count": 1,
                            "comments_count": 0,
                            "shortURL": "Dt",
                            "timestamp": "2017-01-15T16:41:16.000Z",
                            "user": {
                                "name": "Dan Rogers",
                                "id": "55195B5A0BD9E6AC218174AC",
                                "username": "danrogers",
                                "title": "Co-Founder of Linc",
                                "bio": "",
                                "location": "Madrid, Madrid, Spain",
                                "followers_count": 6,
                                "followings_count": 4,
                                "leafs_count": 48,
                                "membersince": "2015-03-30T14:19:06.000Z",
                                "rev": 2,
                                "website": "",
                                "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                                "_links": {
                                    "self": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                                    },
                                    "activities": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                                    },
                                    "followers": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                                    },
                                    "following": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                                    },
                                    "leafed": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/leafed"
                                    },
                                    "posts": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                                    }
                                }
                            },
                            "_links": {
                                "self": {
                                    "href": "/v1/posts/582C59ED4A46D6D7064643C8"
                                },
                                "comments": {
                                    "href": "/v1/posts/582C59ED4A46D6D7064643C8/comments"
                                }
                            }
                        },
                        "leafed_date": "2016-11-17T10:14:46.000Z"
                    },
                    {
                        "post": {
                            "id": "57CD39DD848534652600324A",
                            "source": "http://www.treehugger.com/corporate-responsibility/lets-make-every-weekend-three-day-weekend.html",
                            "title": "Let's make every weekend a three day weekend",
                            "description": "It’s good for the environment and could be for the workers too.",
                            "created_date": "2016-09-05T09:24:45.000Z",
                            "image": "https://cdn.linc.world/articles/57CD39DD848534652600324A.jpg",
                            "rev": 0,
                            "views_count": 100,
                            "leafs_count": 1,
                            "comments_count": 0,
                            "shortURL": "xe",
                            "timestamp": "2017-01-16T20:05:30.000Z",
                            "user": {
                                "name": "Dan Rogers",
                                "id": "55195B5A0BD9E6AC218174AC",
                                "username": "danrogers",
                                "title": "Co-Founder of Linc",
                                "bio": "",
                                "location": "Madrid, Madrid, Spain",
                                "followers_count": 6,
                                "followings_count": 4,
                                "leafs_count": 48,
                                "membersince": "2015-03-30T14:19:06.000Z",
                                "rev": 2,
                                "website": "",
                                "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                                "_links": {
                                    "self": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                                    },
                                    "activities": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                                    },
                                    "followers": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                                    },
                                    "following": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                                    },
                                    "leafed": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/leafed"
                                    },
                                    "posts": {
                                        "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                                    }
                                }
                            },
                            "_links": {
                                "self": {
                                    "href": "/v1/posts/57CD39DD848534652600324A"
                                },
                                "comments": {
                                    "href": "/v1/posts/57CD39DD848534652600324A/comments"
                                }
                            }
                        },
                        "leafed_date": "2016-09-05T16:22:42.000Z"
                    },
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/leafed"
                    },
                    "next": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/leafed?page=2"
                    },
                    "last": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/leafed?page=4"
                    },
                    "user": {
                        "href": "/v1/users/54A05594DFE5D181114C762A"
                    }
                }
            }

### User Activities [/users/{id}/activities{?page,size}]
#### Get Activities [GET]
+ Parameters
    
    + id (required, hexadecimal, `54A05594DFE5D181114C762A`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "activities": [
                    {
                        "id": 3366,
                        "owner_id": "54A05594DFE5D181114C762A",
                        "owner_name": "Pranay Krishen",
                        "user_id": "57C46B27EBEE47694A1ED92C",
                        "user_name": "Antonio Jiménez Martínez",
                        "type": "follow",
                        "post_id": "",
                        "title": "",
                        "created_date": "2017-01-15T15:32:23.000Z"
                    },
                    {
                        "id": 3325,
                        "owner_id": "54A05594DFE5D181114C762A",
                        "owner_name": "Pranay Krishen",
                        "user_id": "54A05594DFE5D181114C762A",
                        "user_name": "Pranay Krishen",
                        "type": "post",
                        "post_id": "5835A14EFE73BC5A3372CF97",
                        "title": "What's Really Warming the World?",
                        "created_date": "2016-11-23T14:01:50.000Z"
                    },
                    {
                        "id": 3257,
                        "owner_id": "54A05594DFE5D181114C762A",
                        "owner_name": "Pranay Krishen",
                        "user_id": "55195B5A0BD9E6AC218174AC",
                        "user_name": "Dan Rogers",
                        "type": "leaf",
                        "post_id": "582C59ED4A46D6D7064643C8",
                        "title": "Solo across the Atlantic in a Folkboat – Yachting World",
                        "created_date": "2016-11-17T10:14:46.000Z"
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                    },
                    "next": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/activities?page=2"
                    },
                    "last": {
                        "href": "/v1/users/54A05594DFE5D181114C762A/activities?page=14"
                    }
                }
            }

### Follow User [/users/{id}/follow]
#### Follow User [POST]
+ Parameters
    
    + id (required, hexadecimal, `54A0E4F54908B9D84E87E4A4`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "54A0E4F54908B9D84E87E4A4",
                "name": "Manu Akash",
                "username": "ManuAkash",
                "title": "UX/UI Engineer at GO-JEK",
                "bio": "I believe strongly in keeping up with, and applying the latest design and technical trends to drive innovation via my work.As a true practitioner of the Latin phrase: \"ACTO NON VERBA\", I believe in letting my efforts speak for themselves.",
                "location": "Bangalore, Karnataka, India",
                "followers_count": 3,
                "followings_count": 6,
                "leafs_count": 150,
                "membersince": "2014-12-29T05:21:57.000Z",
                "rev": 2,
                "website": "",
                "facebook": "https://www.facebook.com/ManuAkash1",
                "google": "https://plus.google.com/+ManuAkash",
                "twitter": "https://twitter.com/ManuAkash1",
                "linkedin": "https://in.linkedin.com/in/manuakash",
                "pinterest": "https://www.pinterest.com/manuakash",
                "views_count": 212,
                "posted_count": 229,
                "following_state": true,
                "interests": {
                    "sectors": [
                        {
                            "Sector": "Energy",
                            "Share": 43
                        }
                    ]
                },
                "image": "https://cdn.linc.world/users/profile-54A0E4F54908B9D84E87E4A4.jpg",
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4"
                    },
                    "activities": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/activities"
                    },
                    "followers": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/followers"
                    },
                    "following": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/following"
                    },
                    "leafed": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/leafed"
                    },
                    "posts": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/posts"
                    }
                }
            }

#### Unfollow User [DELETE]
+ Parameters
    
    + id (required, hexadecimal, `54A0E4F54908B9D84E87E4A4`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "54A0E4F54908B9D84E87E4A4",
                "name": "Manu Akash",
                "username": "ManuAkash",
                "title": "UX/UI Engineer at GO-JEK",
                "bio": "I believe strongly in keeping up with, and applying the latest design and technical trends to drive innovation via my work.As a true practitioner of the Latin phrase: \"ACTO NON VERBA\", I believe in letting my efforts speak for themselves.",
                "location": "Bangalore, Karnataka, India",
                "followers_count": 3,
                "followings_count": 6,
                "leafs_count": 150,
                "membersince": "2014-12-29T05:21:57.000Z",
                "rev": 2,
                "website": "",
                "facebook": "https://www.facebook.com/ManuAkash1",
                "google": "https://plus.google.com/+ManuAkash",
                "twitter": "https://twitter.com/ManuAkash1",
                "linkedin": "https://in.linkedin.com/in/manuakash",
                "pinterest": "https://www.pinterest.com/manuakash",
                "views_count": 212,
                "posted_count": 229,
                "following_state": false,
                "interests": {
                    "sectors": [
                        {
                            "Sector": "Energy",
                            "Share": 43
                        }
                    ]
                },
                "image": "https://cdn.linc.world/users/profile-54A0E4F54908B9D84E87E4A4.jpg",
                "_links": {
                    "self": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4"
                    },
                    "activities": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/activities"
                    },
                    "followers": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/followers"
                    },
                    "following": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/following"
                    },
                    "leafed": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/leafed"
                    },
                    "posts": {
                        "href": "/v1/users/54A0E4F54908B9D84E87E4A4/posts"
                    }
                }
            }

# Group Posts

## Post [/posts/{id}]
### Get Post [GET]
+ Parameters
    
    + id (required, hexadecimal, `581DEDEA002B74604FE091C1`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": "581DEDEA002B74604FE091C1",
                "source": "http://www.autonews.com/article/20161104/OEM05/161109912/teslas-solarcity-deal-gets-a-boost-from-shareholder-advisory-firm",
                "title": "Tesla's SolarCity deal gets a boost from shareholder advisory firm",
                "owner": {
                    "name": "Dan Rogers",
                    "id": "55195B5A0BD9E6AC218174AC",
                    "username": "danrogers",
                    "title": "Co-Founder of Linc",
                    "bio": "",
                    "location": "Madrid, Madrid, Spain",
                    "followers_count": 6,
                    "followings_count": 4,
                    "leafs_count": 48,
                    "membersince": "2015-03-30T14:19:06.000Z",
                    "rev": 2,
                    "website": "",
                    "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                    "_links": {
                        "self": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                        },
                        "activities": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                        },
                        "followers": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                        },
                        "following": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                        },
                        "posts": {
                            "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                        }
                    }
                },
                "description": "Institutional Shareholder Services today recommended that investors in both companies approve Tesla Motors' plan to buy solar panel installer SolarCity for more than $2 billion.",
                "created_date": "2016-11-05T14:34:18.000Z",
                "image": "https://cdn.linc.world/articles/581DEDEA002B74604FE091C1.jpg",
                "rev": 0,
                "height": 172,
                "views_count": 41,
                "leafs_count": 0,
                "comments_count": 0,
                "shortURL": "BG",
                "timestamp": "2017-01-13T00:58:55.000Z",
                "leaf_state": false,
                "_links": {
                    "self": {
                        "href": "/v1/posts/581DEDEA002B74604FE091C1"
                    },
                    "comments": {
                        "href": "/v1/posts/581DEDEA002B74604FE091C1/comments"
                    }
                }
            }

### Post Comments [/posts/{id}/comments{?page,size}]
#### Get Comments [GET]
+ Parameters
    
    + id (required, hexadecimal, `56E1A4C8C6658CBD561ECF05`)
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "comments": [
                    {
                        "id": 25,
                        "user": {
                            "name": "Pranay Krishen",
                            "id": "54A05594DFE5D181114C762A",
                            "username": "pranay",
                            "title": "Founder | Linc",
                            "location": "Madrid, Madrid, Spain",
                            "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                            "_links": {
                                "self": {
                                    "href": "/v1/users/54A05594DFE5D181114C762A"
                                },
                                "activities": {
                                    "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                                },
                                "followers": {
                                    "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                                },
                                "following": {
                                    "href": "/v1/users/54A05594DFE5D181114C762A/following"
                                },
                                "posts": {
                                    "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                                }
                            }
                        },
                        "comment": "<a class=\"user\" target=\"_blank\" href=\"/danrogers\">Dan Rogers</a>  Could you point to any peer-reviewed publications on the subject of climate by any of these 49 signatories?",
                        "leafs_count": 0,
                        "created_date": "2016-03-11T11:43:58.000Z",
                        "meta": "",
                        "flag": 0,
                        "_links": {
                            "self": {
                                "href": "/v1/comments/25"
                            }
                        }
                    },
                    {
                        "id": 26,
                        "user": {
                            "name": "Dan Rogers",
                            "id": "55195B5A0BD9E6AC218174AC",
                            "username": "danrogers",
                            "title": "Co-Founder of Linc",
                            "location": "Madrid, Madrid, Spain",
                            "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                            "_links": {
                                "self": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                                },
                                "activities": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                                },
                                "followers": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                                },
                                "following": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                                },
                                "posts": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                                }
                            }
                        },
                        "comment": "<a class=\"user\" target=\"_blank\" href=\"/pranay\">Pranay Krishen</a>  No.",
                        "leafs_count": 0,
                        "created_date": "2016-03-11T11:45:32.000Z",
                        "meta": "",
                        "flag": 0,
                        "_links": {
                            "self": {
                                "href": "/v1/comments/26"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/posts/56E1A4C8C6658CBD561ECF05/comments"
                    },
                    "post": {
                        "href": "/v1/posts/56E1A4C8C6658CBD561ECF05"
                    }
                }
            }

### Add Comment [/posts/{id}/comments]
#### Add Comment [POST]
+ Parameters
    
    + id (required, hexadecimal, `56E1A4C8C6658CBD561ECF05`)

+ Request (application/json)
            
    + Headers

            Authorization: Bearer <access_token>

    + Body
    
            {
                "comment": "#This is a \n##comment \nthat mentions <@54A05594DFE5D181114C762A>, <@54A05594DFE5D181114C762B> and links <http://example.net/>, <https://www.linc.world/post/Tesla_s_SolarCity_deal_gets_a_boost_from_shareholder_advisory_firm/581DEDEA002B74604FE091C1.html>, <https://linc.world/p/1Z> "
            }

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": 95,
                "user": {
                    "name": "Afzaal Ameer",
                    "id": "54A0117ABD2BE3F251C3492A",
                    "username": "afzaalace",
                    "title": "Evolutionary UX/UI Geek, Entrepreneur, FOSS Contributor",
                    "location": "Madrid, Madrid, Spain",
                    "following_state": false,
                    "image": "https://cdn.linc.world/users/profile-54A0117ABD2BE3F251C3492A.jpg",
                    "_links": {
                        "self": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A"
                        },
                        "activities": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A/activities"
                        },
                        "followers": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A/followers"
                        },
                        "following": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A/following"
                        },
                        "leafed": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A/leafed"
                        },
                        "posts": {
                            "href": "/v1/users/54A0117ABD2BE3F251C3492A/posts"
                        }
                    }
                },
                "post": {
                    "id": "56E1A4C8C6658CBD561ECF05",
                    "title": "Hansen and Schmidt of NASA GISS under fire for climate stance: Engineers, scientists, astronauts ask",
                    "description": "Looks like another GISS miss, more than a few people are getting fed up with Jim Hansen and Gavin Schmidt and their climate shenanigans. Some very prominent NASA voices speak out in a scathing lett…",
                    "created_date": "2016-03-10T16:46:00.000Z",
                    "leafs_count": 1,
                    "comments_count": 6,
                    "shortURL": "dW",
                    "timestamp": "2017-02-08T23:32:19.000Z",
                    "leaf_state": false,
                    "_links": {
                        "self": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05"
                        },
                        "comments": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05/comments"
                        }
                    }
                },
                "comment": "#This is a\ncomment\nthat mentions <@54A05594DFE5D181114C762A>, <@54A05594DFE5D181114C762B> and links <http://Example.net/>, <http://example.net/> \n",
                "leafs_count": 0,
                "created_date": "2017-02-08T23:32:19.000Z",
                "meta": "",
                "flag": 0,
                "leaf_state": false,
                "_links": {
                    "self": {
                        "href": "/v1/comments/95"
                    }
                }
            }

# Group Comments

## Comment [/comments/{id}]
### Get Comment [GET]
+ Parameters
    
    + id (required, number, `25`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": 25,
                "user": {
                    "name": "Pranay Krishen",
                    "id": "54A05594DFE5D181114C762A",
                    "username": "pranay",
                    "title": "Founder | Linc",
                    "location": "Madrid, Madrid, Spain",
                    "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                    "_links": {
                        "self": {
                            "href": "/v1/users/54A05594DFE5D181114C762A"
                        },
                        "activities": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                        },
                        "followers": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                        },
                        "following": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/following"
                        },
                        "posts": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                        }
                    }
                },
                "post": {
                    "id": "56E1A4C8C6658CBD561ECF05",
                    "title": "Hansen and Schmidt of NASA GISS under fire for climate stance: Engineers, scientists, astronauts ask",
                    "description": "Looks like another GISS miss, more than a few people are getting fed up with Jim Hansen and Gavin Schmidt and their climate shenanigans. Some very prominent NASA voices speak out in a scathing lett…",
                    "created_date": "2016-03-10T16:46:00.000Z",
                    "leafs_count": 1,
                    "comments_count": 5,
                    "shortURL": "dW",
                    "timestamp": "2016-12-22T14:12:26.000Z",
                    "_links": {
                        "self": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05"
                        },
                        "comments": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05/comments"
                        }
                    }
                },
                "comment": "<a class=\"user\" target=\"_blank\" href=\"/danrogers\">Dan Rogers</a>  Could you point to any peer-reviewed publications on the subject of climate by any of these 49 signatories?",
                "leafs_count": 0,
                "created_date": "2016-03-11T11:43:58.000Z",
                "meta": "",
                "flag": 0,
                "leaf_state": false,
                "_links": {
                    "self": {
                        "href": "/v1/comments/25"
                    }
                }
            }

### Remove Comment [DELETE]
+ Parameters
    
    + id (required, number, `95`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 204

### Leaf Comment [/comments/{id}/leaf]
#### Leaf Comment [POST]
+ Parameters
    
    + id (required, number, `25`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)

            {
                "id": 25,
                "user": {
                    "name": "Pranay Krishen",
                    "id": "54A05594DFE5D181114C762A",
                    "username": "pranay",
                    "title": "Founder | Linc",
                    "location": "Madrid, Madrid, Spain",
                    "following_state": true,
                    "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                    "_links": {
                        "self": {
                        "href": "/v1/users/54A05594DFE5D181114C762A"
                        },
                        "activities": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                        },
                        "followers": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                        },
                        "following": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/following"
                        },
                        "leafed": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/leafed"
                        },
                        "posts": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                        }
                    }
                },
                "post": {
                    "id": "56E1A4C8C6658CBD561ECF05",
                    "title": "Hansen and Schmidt of NASA GISS under fire for climate stance: Engineers, scientists, astronauts ask",
                    "description": "Looks like another GISS miss, more than a few people are getting fed up with Jim Hansen and Gavin Schmidt and their climate shenanigans. Some very prominent NASA voices speak out in a scathing lett…",
                    "created_date": "2016-03-10T16:46:00.000Z",
                    "leafs_count": 1,
                    "comments_count": 22,
                    "shortURL": "dW",
                    "timestamp": "2017-02-09T00:40:57.000Z",
                    "leaf_state": false,
                    "_links": {
                        "self": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05"
                        },
                        "comments": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05/comments"
                        }
                    }
                },
                "comment": "<a class=\"user\" target=\"_blank\" href=\"/danrogers\">Dan Rogers</a>  Could you point to any peer-reviewed publications on the subject of climate by any of these 49 signatories?",
                "leafs_count": 1,
                "created_date": "2016-03-11T11:43:58.000Z",
                "meta": "",
                "flag": 0,
                "leaf_state": true,
                    "_links": {
                    "self": {
                        "href": "/v1/comments/25"
                    }
                }
            }
            
#### Unleaf Comment [DELETE]
+ Parameters
    
    + id (required, number, `25`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)

            {
                "id": 25,
                "user": {
                    "name": "Pranay Krishen",
                    "id": "54A05594DFE5D181114C762A",
                    "username": "pranay",
                    "title": "Founder | Linc",
                    "location": "Madrid, Madrid, Spain",
                    "following_state": true,
                    "image": "https://cdn.linc.world/users/profile-54A05594DFE5D181114C762A.jpg",
                    "_links": {
                        "self": {
                        "href": "/v1/users/54A05594DFE5D181114C762A"
                        },
                        "activities": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/activities"
                        },
                        "followers": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/followers"
                        },
                        "following": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/following"
                        },
                        "leafed": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/leafed"
                        },
                        "posts": {
                            "href": "/v1/users/54A05594DFE5D181114C762A/posts"
                        }
                    }
                },
                "post": {
                    "id": "56E1A4C8C6658CBD561ECF05",
                    "title": "Hansen and Schmidt of NASA GISS under fire for climate stance: Engineers, scientists, astronauts ask",
                    "description": "Looks like another GISS miss, more than a few people are getting fed up with Jim Hansen and Gavin Schmidt and their climate shenanigans. Some very prominent NASA voices speak out in a scathing lett…",
                    "created_date": "2016-03-10T16:46:00.000Z",
                    "leafs_count": 1,
                    "comments_count": 22,
                    "shortURL": "dW",
                    "timestamp": "2017-02-09T00:40:57.000Z",
                    "leaf_state": false,
                    "_links": {
                        "self": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05"
                        },
                        "comments": {
                            "href": "/v1/posts/56E1A4C8C6658CBD561ECF05/comments"
                        }
                    }
                },
                "comment": "<a class=\"user\" target=\"_blank\" href=\"/danrogers\">Dan Rogers</a>  Could you point to any peer-reviewed publications on the subject of climate by any of these 49 signatories?",
                "leafs_count": 1,
                "created_date": "2016-03-11T11:43:58.000Z",
                "meta": "",
                "flag": 0,
                "leaf_state": false,
                    "_links": {
                    "self": {
                        "href": "/v1/comments/25"
                    }
                }
            }


# Group Notifications - Needs more work

## User Notifications [/notifications{?page,size}]
### Get Notifications [GET]

+ Parameters
    
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "notifications": [
                    {
                        "id": 12873,
                        "activity": 3366,
                        "user": "54A0117ABD2BE3F251C3492A",
                        "user_name": "Afzaal Ameer",
                        "owner_id": "54A05594DFE5D181114C762A",
                        "owner_name": "Pranay Krishen",
                        "type": "followFollowed",
                        "post": "",
                        "title": "",
                        "other_id": "57C46B27EBEE47694A1ED92C",
                        "other_name": "Antonio Jiménez Martínez",
                        "param": "",
                        "status": -1,
                        "timestamp": "2017-01-15T15:32:23.000Z"
                    },
                    {
                        "id": 12626,
                        "activity": 3325,
                        "user": "54A0117ABD2BE3F251C3492A",
                        "user_name": "Afzaal Ameer",
                        "owner_id": "54A05594DFE5D181114C762A",
                        "owner_name": "Pranay Krishen",
                        "type": "post",
                        "post": "5835A14EFE73BC5A3372CF97",
                        "title": "What's Really Warming the World?",
                        "other_id": "",
                        "other_name": "",
                        "param": "",
                        "status": -1,
                        "timestamp": "2016-11-23T14:01:50.000Z"
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/notifications"
                    },
                    "next": {
                        "href": "/v1/notifications?page=2"
                    },
                    "last": {
                        "href": "/v1/notifications?page=21"
                    }
                }
            }

## Notification [/notifications/{id}]
### Get Notification [GET]
+ Parameters
    
    + id (required, number, `25`)

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "id": 12873,
                "activity": 3366,
                "user": "54A0117ABD2BE3F251C3492A",
                "user_name": "Afzaal Ameer",
                "owner_id": "54A05594DFE5D181114C762A",
                "owner_name": "Pranay Krishen",
                "type": "followFollowed",
                "post": "",
                "title": "",
                "other_id": "57C46B27EBEE47694A1ED92C",
                "other_name": "Antonio Jiménez Martínez",
                "param": "",
                "status": -1,
                "timestamp": "2017-01-15T15:32:23.000Z"
            }

# Group Feed

## User Feed [/feed{?page,size}]
### Get Feed [GET]

+ Parameters
    
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "posts": [
                    {
                        "image": "https://cdn.linc.world/articles/58515AA20A5E7CB347616F1B.jpg",
                        "shortURL": "F6",
                        "comments_count": 0,
                        "description": "2016 has been a big year for the global energy storage market.",
                        "source": "http://www.eca-group.co.uk/2016/11/adopt-battery-storage/",
                        "created_date": "2016-12-14T14:43:46.000Z",
                        "views_count": 109,
                        "title": "Businesses and homes across the world adopt battery storage",
                        "leafs_count": 0,
                        "id": "58515AA20A5E7CB347616F1B",
                        "user": {
                            "name": "Neil Maycock",
                            "id": "585159A80A5E7CB347616F1A",
                            "username": "",
                            "title": "",
                            "bio": "",
                            "location": "",
                            "followers_count": 0,
                            "followings_count": 0,
                            "leafs_count": 0,
                            "membersince": 1481726376,
                            "rev": 0,
                            "website": "",
                            "image": "https://cdn.linc.world/users/profile-585159A80A5E7CB347616F1A.jpg",
                            "_links": {
                                "self": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A"
                                },
                                "activities": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A/activities"
                                },
                                "followers": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A/followers"
                                },
                                "following": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A/following"
                                },
                                "leafed": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A/leafed"
                                },
                                "posts": {
                                    "href": "/v1/users/585159A80A5E7CB347616F1A/posts"
                                }
                            }
                        },
                        "_links": {
                            "self": {
                                "href": "/v1/posts/58515AA20A5E7CB347616F1B"
                            },
                            "comments": {
                                "href": "/v1/posts/58515AA20A5E7CB347616F1B/comments"
                            }
                        }
                    },
                    {
                        "image": "https://cdn.linc.world/articles/58386A97068EB55C12E4C25F.jpg",
                        "shortURL": "F3",
                        "comments_count": 0,
                        "description": "Finland plans to stop using coal in the 2020s, aiming for carbon neutrality as soon as 2050.",
                        "source": "http://inhabitat.com/finland-may-be-the-first-country-to-completely-ban-coal/",
                        "created_date": "2016-11-25T16:45:11.000Z",
                        "views_count": 151,
                        "title": "Finland may be the first country to completely ban coal",
                        "leafs_count": 0,
                        "id": "58386A97068EB55C12E4C25F",
                        "user": {
                            "name": "Dan Rogers",
                            "id": "55195B5A0BD9E6AC218174AC",
                            "username": "danrogers",
                            "title": "Co-Founder of Linc",
                            "bio": "",
                            "location": "Madrid, Madrid, Spain",
                            "followers_count": 6,
                            "followings_count": 4,
                            "leafs_count": 48,
                            "membersince": 1427725146,
                            "rev": 2,
                            "website": "",
                            "image": "https://cdn.linc.world/users/profile-55195B5A0BD9E6AC218174AC.jpg",
                            "_links": {
                                "self": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC"
                                },
                                "activities": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/activities"
                                },
                                "followers": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/followers"
                                },
                                "following": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/following"
                                },
                                "leafed": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/leafed"
                                },
                                "posts": {
                                    "href": "/v1/users/55195B5A0BD9E6AC218174AC/posts"
                                }
                            }
                        },
                        "_links": {
                            "self": {
                                "href": "/v1/posts/58386A97068EB55C12E4C25F"
                            },
                            "comments": {
                                "href": "/v1/posts/58386A97068EB55C12E4C25F/comments"
                            }
                        }
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/feed/"
                    },
                    "next": {
                        "href": "/v1/feed/?page=2"
                    },
                    "last": {
                        "href": "/v1/feed/?page=114"
                    }
                }
            }


# Group Search

## Search [/search{?q,page,size}]
### Search [GET]

+ Parameters
    
    + q (required, string, `blue`) - Query for search
    + page (optional, number) - Page number for pagination, default: 1
    + size (optional, number) - Items per page, default: 20

+ Request
            
    + Headers

            Authorization: Bearer <access_token>

+ Response 200 (application/json)
    
    + Body
        
            {
                "results": [
                    {
                        "type": "post",
                        "id": "56CF0403EB3EAC8B3B333E25",
                        "title": "Roving Blue, Inc. Announces Key Additions to their Advisory Board | Roving Blue"
                    },
                    {
                        "type": "post",
                        "id": "56C3538AEB2627240F4B8D4E",
                        "title": "Army Expeditionary Warrior Experiments (AEWE) Test Roving Blue Water Purifier in the Field"
                    },
                    {
                        "type": "post",
                        "id": "5758808299AC4E1E0D12491E",
                        "title": "World Oceans Day: Healthy Oceans = Healthy Planet"
                    },
                    {
                        "type": "post",
                        "id": "56EEB9E1EC08916473945720",
                        "title": "Chile has 24,133 glaciers, and we’re losing them piece by piece"
                    },
                    {
                        "type": "post",
                        "id": "56DBFBB31547640064811543",
                        "title": "\nThe Plight of Bluefin Tunas | Stanford Woods Institute\t\t"
                    },
                    {
                        "type": "post",
                        "id": "56A88BAFE95498CA74B76DB7",
                        "title": "In Japan, a David vs Goliath Battle to Preserve Bluefin Tuna  by Winifred Bird: Yale Environment 360"
                    },
                    {
                        "type": "post",
                        "id": "576AE344C105A89D59A7AC58",
                        "title": "Diablo Canyon Nuclear Reactors to Be Replaced With 100 percent Renewable Energy"
                    },
                    {
                        "type": "user",
                        "id": "56C350798728ACAD0EF3BAAA",
                        "name": "Meli Lussier",
                        "title": "Sales, Marketing &amp; Social Media - Roving Blue"
                    },
                    {
                        "type": "user",
                        "id": "56C427253C5743F937D004E2",
                        "name": "Rudi van Arend",
                        "title": "International Sales Manager at Roving Blue"
                    }
                ],
                "_links": {
                    "self": {
                        "href": "/v1/search/?q=blue"
                    }
                }
            }